ansible-collections/ibm_zos_cics

- docs/source/modules/cmci_action.rst
- plugins/module_utils/cmci.py
- plugins/modules/cmci_action.py
- plugins/modules/cmci_create.py
- plugins/modules/cmci_delete.py
- plugins/modules/cmci_get.py
- plugins/modules/cmci_update.py
- tests/integration/targets/cics_cmci/cmci-variables.yml.template
- tests/integration/targets/cics_cmci/playbooks/cics_cmci.yml
- tests/unit/modules/test_cmci_action.py
> Generic action support

- plugins/module_utils/cmci.py
> Fix warnings and merge issues

- docs/source/modules/cmci_action.rst
- docs/source/modules/cmci_create.rst
- docs/source/modules/cmci_delete.rst
- docs/source/modules/cmci_get.rst
- docs/source/modules/cmci_update.rst
- plugins/doc_fragments/cmci.py
- plugins/module_utils/cmci.py
- plugins/modules/cmci_action.py
- plugins/modules/cmci_create.py
- plugins/modules/cmci_delete.py
- plugins/modules/cmci_get.py
- plugins/modules/cmci_update.py
- tests/integration/targets/cics_cmci/playbooks/cics_cmci.yml
- tests/unit/modules/test_cmci_action.py
- tests/unit/modules/test_cmci_delete.py
- tests/unit/modules/test_cmci_get.py
- tests/unit/modules/test_cmci_update.py
> Support params for GET the same as for actions

- plugins/module_utils/cmci.py
- tests/unit/modules/test_cmci_filters.py
> Use ansible to validate complex filters, share defs

- plugins/module_utils/cmci.py
- tests/integration/targets/cics_cmci/playbooks/cics_cmci.yml
- tests/integration/targets/cics_cmci/playbooks/cmci_insecure_false.yml
- tests/integration/targets/cics_cmci/runme.sh
> Default to verify SSL = true, allow user override

- docs/source/index.rst
- docs/source/installation.rst
- docs/source/modules/cmci_action.rst
- docs/source/modules/cmci_create.rst
- docs/source/modules/cmci_delete.rst
- docs/source/modules/cmci_get.rst
- docs/source/modules/cmci_update.rst
- docs/source/release_notes.rst
- docs/source/requirements.rst
- docs/source/requirements_managed.rst
- plugins/doc_fragments/cmci.py
- plugins/modules/cmci_action.py
- plugins/modules/cmci_create.py
- plugins/modules/cmci_delete.py
- plugins/modules/cmci_get.py
- plugins/modules/cmci_update.py
Update common doc fragments for modules.
Update doc for the action module.
Some wording changes to follow the style of other collections.
```paste below
```
> update modules doc and minor changes to address comments

- docs/ansible_content.rst
- docs/source/index.rst
- docs/source/installation.rst
- docs/source/modules.rst
- docs/source/modules/cmci_action.rst
- docs/source/modules/cmci_create.rst
- docs/source/modules/cmci_delete.rst
- docs/source/modules/cmci_get.rst
- docs/source/modules/cmci_update.rst
- docs/source/release_notes.rst
- docs/source/requirements.rst
- docs/source/requirements_managed.rst
- plugins/doc_fragments/cmci.py
- plugins/modules/cmci_action.py
- plugins/modules/cmci_create.py
- plugins/modules/cmci_delete.py
- plugins/modules/cmci_get.py
- plugins/modules/cmci_update.py
Updates descriptions for these parameters: context, attributes, record_count
Update the requirements of managed node so we don't say No SSH explicitly. 
> fixes for some module parameters, rephrase requirements on managed node, mark trademarks

- README.md
- docs/source/modules/cmci_action.rst
- docs/source/modules/cmci_create.rst
- docs/source/modules/cmci_update.rst
- plugins/modules/cmci_action.py
- plugins/modules/cmci_create.py
- plugins/modules/cmci_update.py
doc cleanup with minor wording changes (for new "parameters" in modules doc), trademarks in readme
```
> doc cleanup,minor wording changes, trademarks in readme

- CONTRIBUTING.md
- README.md
- docs/ansible_content.rst
- docs/source/community_guides.rst
- docs/source/installation.rst
- docs/source/modules/cmci_action.rst
- docs/source/modules/cmci_create.rst
- docs/source/modules/cmci_delete.rst
- docs/source/modules/cmci_get.rst
- docs/source/modules/cmci_update.rst
- docs/source/requirements.rst
- docs/source/requirements_managed.rst
- plugins/doc_fragments/cmci.py
- plugins/modules/cmci_create.py
To adress doc issues identified by the review
Details can be found here: https://trello.com/c/IrzZ7NBS
> address doc issues from review

- tests/integration/targets/cics_cmci/playbooks/cmci_bas_link.yml
- tests/integration/targets/cics_cmci/runme.sh
Integration test creates resource for a basic BAS configuration and tests the resource description is linked to the program
> Basic BAS setup and link test

- README.md
> Extra '{' in README

- tests/integration/targets/cics_cmci/playbooks/cmci_bas_install.yml
- tests/integration/targets/cics_cmci/runme.sh
IT test that deploys program def into target and related scopes checking where it will be installed
> Full BAS integration test

- docs/source/release_notes.rst
- galaxy.yml
> Bump version to 0.0.2

- galaxy.yml
> Exclude unnecessary files from galaxy package

- docs/source/community_guides.rst
- docs/source/modules/cmci_action.rst
- docs/source/modules/cmci_delete.rst
- docs/source/modules/cmci_get.rst
- docs/source/modules/cmci_update.rst
- docs/source/release_notes.rst
- docs/source/requirements_managed.rst
- plugins/doc_fragments/cmci.py
Update links to our doc site, samples repo, devguide, etc in requirements and release notes.
Minor editorial changes to filter / complex_filter entries in Modules doc:
- Default: EQ for complex_filter
- Add periords at the end of sentences.
> update/fix links, minor editorial changes to filter doc

- docs/source/modules/cmci_action.rst
- docs/source/modules/cmci_delete.rst
- docs/source/modules/cmci_get.rst
- docs/source/modules/cmci_update.rst
- plugins/doc_fragments/cmci.py
Remove the restriction to nesting layer being at most 4 from module doc.
> remove nesting layer restriction

- docs/source/release_notes.rst
- docs/source/requirements_managed.rst
Provide two code snippets to install python dependencies for python >= and < 3.5
Update release note to include Automation Hub
> update code snippet to include dependency typing, update release note

- plugins/modules/cmci_action.py
- plugins/modules/cmci_create.py
- plugins/modules/cmci_delete.py
- plugins/modules/cmci_get.py
- plugins/modules/cmci_update.py
> Address issues with examples

- README.md
- docs/source/release_notes.rst
Update link to sample playbooks to point to the updated README/main page on their master branch.
> update links to sample playbook repo

- plugins/doc_fragments/cmci.py
- plugins/module_utils/cmci.py
> Add configurable timeout support

- plugins/modules/cmci_get.py
> Fix name of resources parameter in example

- plugins/doc_fragments/cmci.py
- plugins/module_utils/cmci.py
- prod-requirements.txt
> Fix pep8 sanity tests

- Dockerfile
> Add missing backports lib for virtualenv

- docs/Makefile
- docs/source/.gitignore
> Run ansible doc extractor when making html for docs

- docs/Makefile
- docs/source/modules/cmci_action.rst
- docs/source/modules/cmci_create.rst
- docs/source/modules/cmci_delete.rst
- docs/source/modules/cmci_get.rst
- docs/source/modules/cmci_update.rst
Signed-off-by: ddimatos <dimatos@gmail.com>
Accept at will.
Used the Makefile I have in ibm_zos_core to generate the RST with no issues. I pushed the Makefile and RST accept or take what you want from this PR. 
> Use core's Makefile to generate RST

- plugins/doc_fragments/cmci.py
Signed-off-by: Vera Chan <vera.xx.c@me.com>
Fix #107 
generic content shared by all CMCI modules
Fixed the incorrect italic formatting of some "cmci_password" instances
```paste below
```
> fix italic formating

- docs/source/release_notes.rst
Removed all the beta releases sections.
Updated Version 2.1.0 What's new text
Not applicable. Editorial changes to documentation only.
```paste below
```
> Update release_notes.rst - cssh

- docs/ansible-doc-extractor-collections.py
- docs/source/modules/cmci_action.rst
- docs/source/modules/cmci_create.rst
- docs/source/modules/cmci_delete.rst
- docs/source/modules/cmci_get.rst
- docs/source/modules/cmci_update.rst
- plugins/modules/cmci_action.py
- plugins/modules/cmci_create.py
- plugins/modules/cmci_delete.py
- plugins/modules/cmci_get.py
- plugins/modules/cmci_update.py
- tests/integration/targets/cics_data_set/playbooks/validation_template.yml
- tests/integration/targets/cics_region_jcl/playbooks/region_jcl_member.yml
- tests/integration/targets/cics_start_stop/playbooks/stop_args.yml
- tests/integration/targets/cics_start_stop/playbooks/validate_console_autoinstall_fail.yml
- tests/integration/targets/cics_start_stop/playbooks/validate_console_not_defined.yml
- tests/integration/targets/cics_start_stop/repeatable_tasks/stop_region.yml
Looks like rst files hadnt been regened in a while, got a few additional changes to those
> Fix Ansible sanity tests with new version bump

- docs/source/modules.rst
- docs/source/requirements.rst
- plugins/plugin_utils/_module_action_plugin.py
- tests/integration/targets/cics_templating/playbook.yml
- tests/integration/targets/cics_templating/roles/aux_temp_storage/action_plugins/process_input.py
- tests/integration/targets/cics_templating/roles/aux_temp_storage/meta/argument_specs.yml
- tests/integration/targets/cics_templating/roles/aux_temp_storage/meta/main.yml
- tests/integration/targets/cics_templating/roles/aux_temp_storage/tasks/main.yml
- tests/integration/targets/cics_templating/runme.sh
Fix custom templating in newer versions of ansible. Have added a single line where we describe the custom templating in the doc about a known limitation. I would also want to add this to the release notes for the next release but havent done that here.
Also includes a role style integration test that we've been able to reproduce the templating problem in consistently.
> Custom templating fix

- README.md
Added some components to the readme to match new standards.
Think I'd like some opinions specifically on the use cases too please as I am not 100%. Thanks!
> Change Readme to new certified collection format

- README.md
- Bugfix Pull Request
- Feature Pull Request
- New Module Pull Request
```paste below
```
> camel case and copyright in documentation read me 

- plugins/module_utils/_data_set.py
- plugins/module_utils/_zoau_version_checker.py
- plugins/modules/stop_region.py
- tests/unit/module_utils/test_zoau_version_checker.py
- tests/unit/modules/test_aux_temp_storage.py
- tests/unit/modules/test_aux_trace.py
- tests/unit/modules/test_csd.py
- tests/unit/modules/test_global_catalog.py
- tests/unit/modules/test_local_catalog.py
- tests/unit/modules/test_local_request_queue.py
- tests/unit/modules/test_region_jcl.py
- tests/unit/modules/test_stop_region.py
- tests/unit/modules/test_td_intrapartition.py
- tests/unit/modules/test_transaction_dump.py
Adds ZOAU compatibility utility to all modules needing ZOAU functionality
> Add zoau compatibility util

- docs/source/modules/region_jcl.rst
- plugins/doc_fragments/region_jcl.py
- plugins/modules/region_jcl.py
Added OTELTRACE,SECURETCPIP sit parameters
- Feature Pull Request
> Added OTELTRACE,SECURETCPIP sit parameters

- requirements.txt
- Bugfix Pull Request
- Feature Pull Request
- New Module Pull Request
```paste below
```
> Bumped to latest xmltodict to pickup CVE fix

- CHANGELOG.rst
- README.md
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- docs/source/conf.py
- docs/source/release_notes.rst
- galaxy.yml
- meta/ibm_zos_cics_meta.yml
- Bugfix Pull Request
- Feature Pull Request
- New Module Pull Request
```paste below
```
> Bump release to version 2.2.1
